# Generated by Django 4.1.3 on 2022-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=20)),
                ('exchangerate', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
