# Generated by Django 4.1.3 on 2022-12-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlarm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('yen_price', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='alarm.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnOffRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_alarm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.useralarm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
